### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by PanduZen** [Marc0ai/sd-webui-photo-refiner#1]
I have installed the extension but I don't see anything new in the ui, I am using forge.

**Comment by Marc0ai** [comment]
After installation and reloading the UI this new section should appear:
![Immagine 2024-09-17 145557](https://github.com/user-attachments/assets/f736971b-ef7c-4913-9751-a5a91c15d323)

**Comment by PanduZen** [comment]
Ok, I have looked at the log and it tells me that it could not find “dlib”, how do I install it?

**Comment by Marc0ai** [comment]
I had to temporarily disable the "face refiner" until I solve the dlib problem, now it is no longer necessary and the extension should work correctly, feel free to update it and let me know
To avoid further problems, I advise you to remove it and reinstall it.

**Comment by PanduZen** [comment]
now works perfectly, thank you!

**Comment by PanduZen** [comment]
I tried it with a photo lowering the shadows and the result was incredible, it's just what I was looking for.

By the way, do you plan to make it compatible with X/Y/X, I would really like to make comparisons with different strengths in the presets.

**Comment by Marc0ai** [comment]
I'm happy that everything is working now, glad to hear that.
As for x/y/z, I can take a look at it, but I'm at a rather novice level, I have to understand how everything works, but I don't rule out the possibility of including it in the future.

**Comment by PanduZen** [comment]
> I'm happy that everything is working now, glad to hear that. As for x/y/z, I can take a look at it, but I'm at a rather novice level, I have to understand how everything works, but I don't rule out the possibility of including it in the future.

I just noticed that when the image is saved, it is saved without the filter active, is this normal?

I have to save it manually every time I generate an image, it can be a problem when I want to generate several images with the same filter, and I will surely forget to save them manually. 

Is it possible to save them with the filter?

**Comment by Marc0ai** [comment]
I updated, now you can find all the "refined" photos in "output/photo_refiner_outputs".
Unfortunately there is no distinction between txt2img and img2img, but I don't think it's that big of a problem.
Enjoy 👍

**Comment by PanduZen** [comment]
Insane dude, thanks for all
