### ISSUE TITLE
A typo and a filter suggestion

### ISSUE THREAD

**Issue by SvenErik1968** [Marc0ai/sd-webui-photo-refiner#2]
You have a small typo in README.md file. The link "Stauration" I guess should be "Saturation" ;-)
![image](https://github.com/user-attachments/assets/964ea481-290e-4760-b432-195bd4c0bf1b)

I also have a suggestion for a new filter, making it sepia tinted. Found [this code snippet](https://stackoverflow.com/a/75618572) using `PIL` and `numpy` (much faster!) on StackOverflow, and [this article](https://fxis.ai/edu/how-to-apply-a-sepia-filter-to-images-using-python/).

**Comment by Marc0ai** [comment]
why not...
updated, sepia included

**Comment by SvenErik1968** [comment]
Great!
